using System;
using System.Collections.Generic;
using System.Linq;

namespace UrbanoMetraj.BoQ.Models
{
    // =========================================================================
    // Phase 1 – Pipe and Manhole aggregation models
    // =========================================================================

    public class PipeItem
    {
        public int    Diameter                { get; set; }  // mm
        public string Material                { get; set; }
        public double TotalLength             { get; set; }  // m  (2-D from @pos coordinates)
        public double TotalExcavationVolume   { get; set; }  // m³  total trench excavation (after clash deduction)
        public double TotalBeddingVolume      { get; set; }  // m³  bedding sand layer
        public double TotalSurroundVolume     { get; set; }  // m³  pipe surround sand (net of pipe)
        public double TotalBackfillVolume     { get; set; }  // m³  compacted backfill (after clash deduction)
        public double OverlapVolumeDeducted   { get; set; }  // m³  50/50 deducted due to trench clash
    }

    /// <summary>
    /// One row = one physical manhole node (no grouping).
    /// Phase 2 fields are populated by ManholeAIService.Process().
    /// </summary>
    public class ManholeItem
    {
        // ── Identity & geometry ───────────────────────────────────────────────
        public string NodeName           { get; set; }  // AG_NAME  (e.g. "1Y", "4Y")
        public double X                  { get; set; }  // easting  (m)
        public double Y                  { get; set; }  // northing (m)
        public double TerrainElevation   { get; set; }  // TH1      (m, a.s.l.)
        public double Depth              { get; set; }  // computed manhole depth (m)
        public int    Diameter           { get; set; }  // nominal shaft Ø (mm)

        // kept for summary totals / backwards compat
        public int    Count              { get; set; } = 1;
        public double TotalDepth         => Depth;
        public double AverageDepth       => Depth;

        // ── Phase 2 – Manhole AI topology ────────────────────────────────────
        /// <summary>Number of inlet sections that are NOT drop-pipes.</summary>
        public int    ValidInletCount    { get; set; }
        /// <summary>Number of outlet sections.</summary>
        public int    ValidOutletCount   { get; set; }
        /// <summary>True if at least one inlet is classified as a drop-pipe.</summary>
        public bool   HasDropPipe        { get; set; }
        /// <summary>
        /// Human-readable type string generated by ManholeAIService.
        /// Example: "Baca O1000 - (2 Giris / 1 Cikis)"
        /// Null until ManholeAIService.Process() has been called.
        /// </summary>
        public string SmartTypeName      { get; set; }
        /// <summary>Pre-cast stacking result. Null if catalog missing or AI not yet run.</summary>
        public ManholeStackResult StackPreCast     { get; set; }
        /// <summary>Cast-in-place stacking result (ConcreteDepth). Null if AI not yet run.</summary>
        public ManholeStackResult StackCastInPlace { get; set; }
        /// <summary>Backward-compat accessor (PreCast wins if available).</summary>
        public ManholeStackResult Stack => StackPreCast ?? StackCastInPlace;
    }

    public class SystemBoQ
    {
        public string            SystemName { get; set; }
        public List<PipeItem>    Pipes      { get; set; } = new List<PipeItem>();
        public List<ManholeItem> Manholes   { get; set; } = new List<ManholeItem>();
    }

    // =========================================================================
    // Phase 1 – Per-station cross-section data (computed every ~5 m along pipe)
    // =========================================================================

    public class CrossSectionStation
    {
        public double StationDist   { get; set; }  // distance from start node (m)
        public double WorldX        { get; set; }
        public double WorldY        { get; set; }
        public double TerrainZ      { get; set; }
        public double InvertZ       { get; set; }
        public double TrueDepth     { get; set; }  // depthToInvert + TrBedHeight
        public double TopWidthExcav { get; set; }  // TrWidth + 2*TrueDepth*SlopeRatio

        // ── Polygon vertices in local (U, Z) frame ─────────────────────────────
        // U = 0 is the pipe centreline axis; U is the signed perpendicular offset.
        // Each element: double[2] { U, Z }.  CCW winding.
        public List<double[]> ExcavPoly    { get; set; }   // full excavation trapezoid
        public List<double[]> BeddingPoly  { get; set; }   // bedding sand layer
        public List<double[]> SurroundPoly { get; set; }   // pipe surround (gross — includes pipe void)
        public List<double[]> BackfillPoly { get; set; }   // backfill zone above surround

        // ── Overlap-adjusted polygons (null = no overlap, or this pipe wins) ────
        // ExcavPolyModified is the REMAINING polygon after the overlap zone is
        // removed — i.e. the actual cross-section shape to loft into a 3-D solid.
        // null means either HasOverlap=false or this pipe is assigned full ownership
        // of the overlap zone (LowerPipe/UpperPipe wins), so ExcavPoly is used as-is.
        public List<double[]> ExcavPolyModified    { get; set; }
        public List<double[]> BackfillPolyModified { get; set; }

        // ── Cross-section areas (m²) computed from polygons ───────────────────
        public double AreaExcav    { get; set; }   // PolygonArea(ExcavPoly)
        public double AreaBedding  { get; set; }   // PolygonArea(BeddingPoly)
        public double AreaSurround { get; set; }   // PolygonArea(SurroundPoly) − PipeArea (net)
        public double AreaBackfill { get; set; }   // PolygonArea(BackfillPoly)

        // ── Net areas after per-station overlap deduction ─────────────────────
        // Equal to the gross areas above when HasOverlap is false.
        public double AreaExcavNet    { get; set; }
        public double AreaBackfillNet { get; set; }

        public bool HasOverlap { get; set; }

        /// <summary>
        /// True when this station was synthetically injected at the exact boundary
        /// (entry or exit) of a crossing zone between two pipes.
        /// Interior stations inside the crossing zone are NOT marked — only the
        /// two boundary stations per crossing pair are marked on each pipe.
        /// Downstream commands can use this to annotate cross-sections, highlight
        /// boundary positions in 3-D, or drive special labelling in reports.
        /// </summary>
        public bool IsCrossingBoundary { get; set; }

        // ── Pseudo-3D engine (Clipper2) — "Pre-calculate and Cache" ──────────────
        // The new Phase 3 orchestrator fills these at URBANO_BOQ time; the legacy
        // *PolyModified fields above are retained only for backward compatibility
        // with old DWGs and are not produced by the new engine.
        //
        // For EVERY station we cache the fully-resolved geometry + net area of all
        // four layers under ALL THREE preference scenarios. Downstream commands
        // (solids, cross-section plotting) and the results-dialog drop-down just
        // read the matching ScenarioProfile — no Clipper booleans are re-run.
        // See TrenchGeometry.cs / ClipperGeo.cs.

        /// <summary>Solid pipe-body cross-section as an N-gon in (U,Z). Deducted from
        /// Bedding/Surround/Backfill — never from Excavation.</summary>
        public List<double[]> PipeBodyPoly { get; set; }

        /// <summary>Cached resolved profile — preference "Keep Upper" (shallower wins ties).</summary>
        public ScenarioProfile ScenarioKeepUpper { get; set; }
        /// <summary>Cached resolved profile — preference "Keep Lower" (deeper wins ties).</summary>
        public ScenarioProfile ScenarioKeepLower { get; set; }
        /// <summary>Cached resolved profile — preference "50/50 vertical split".</summary>
        public ScenarioProfile ScenarioSplit { get; set; }

        /// <summary>Returns the cached profile for the given preference.</summary>
        public ScenarioProfile Scenario(TiePreference p)
        {
            switch (p)
            {
                case TiePreference.KeepUpper: return ScenarioKeepUpper;
                case TiePreference.KeepLower: return ScenarioKeepLower;
                case TiePreference.Ignore:    return null;
                default:                      return ScenarioSplit;
            }
        }
    }

    // =========================================================================
    // Phase 1 – Per-section excavation debug row
    // =========================================================================

    public class SectionDebugRow
    {
        // ── Identity ─────────────────────────────────────────────────────────
        public string SystemName      { get; set; }
        public string PipeName        { get; set; }   // "1Y → 2Y"
        /// <summary>Phase 2 topology — start node name from the parser.</summary>
        public string StartNodeName   { get; set; }
        /// <summary>Phase 2 topology — end node name from the parser.</summary>
        public string EndNodeName     { get; set; }
        /// <summary>Start/end node (manhole) GUIDs from the Urbano topology. Used by
        /// the overlap engine to skip clashes between pipes sharing a manhole
        /// (connected pipes never count as a real trench clash). Compute-time only —
        /// not serialised, since overlap resolution runs before the data is saved.</summary>
        public string StartNodeGuid   { get; set; }
        public string EndNodeGuid     { get; set; }
        public int    DiameterMm      { get; set; }
        public string Material        { get; set; }   // for re-aggregating PipeItems from cache
        public double PipeOuterDiamM  { get; set; }
        public double Length2D        { get; set; }

        // ── Node world coordinates (for 3-D solid generation) ─────────────────
        public double StartX          { get; set; }
        public double StartY          { get; set; }
        public double StartTerrainZ   { get; set; }   // TH1 at start node
        public double EndX            { get; set; }
        public double EndY            { get; set; }
        public double EndTerrainZ     { get; set; }   // TH1 at end node

        // ── Elevation inputs ─────────────────────────────────────────────────
        public double InvertStart     { get; set; }
        public double InvertEnd       { get; set; }
        public double DepthToInvStart { get; set; }
        public double DepthToInvEnd   { get; set; }

        // ── Trench catalog ────────────────────────────────────────────────────
        public double TrWidth         { get; set; }
        public double TrBedHeight     { get; set; }
        public double TrSandOverPipe  { get; set; }
        public double TrAngleL        { get; set; }
        public double TrAngleR        { get; set; }

        // ── Constant cross-section ────────────────────────────────────────────
        public double SlopeRatio      { get; set; }
        public double TopWidthBed     { get; set; }
        public double ABed            { get; set; }
        public double HSurround       { get; set; }
        public double BaseWidthSurr   { get; set; }
        public double TopWidthSurr    { get; set; }
        public double ASurroundGross  { get; set; }
        public double PipeArea        { get; set; }
        public double ASurroundNet    { get; set; }

        // ── Variable cross-section ────────────────────────────────────────────
        public double TrueDepthStart  { get; set; }
        public double TrueDepthEnd    { get; set; }
        public double TopWidthExcavS  { get; set; }
        public double TopWidthExcavE  { get; set; }
        public double AExcavStart     { get; set; }
        public double AExcavEnd       { get; set; }
        public double ABackfillStart  { get; set; }
        public double ABackfillEnd    { get; set; }

        // ── Volumes ───────────────────────────────────────────────────────────
        public double VBedding              { get; set; }
        public double VSurround             { get; set; }
        public double VExcav                { get; set; }
        public double VBackfill             { get; set; }

        // ── Clash detection ───────────────────────────────────────────────────
        public double OverlapVolumeDeducted { get; set; }
        public List<string> ClashLog        { get; set; } = new List<string>();

        // ── Integration-averaging corrections (set by ApplyExcavationAveraging) ──
        // Volume adjustment (m³) added to the raw trapezoidal integral under each
        // excavation scenario. Eliminates the discretization asymmetry that arises
        // because integrating the same 3-D intersection along two different pipe
        // axes gives slightly different floating-point sums. Zero until that pass
        // runs; preserved across RecomputeRow calls so dropdown changes stay exact.
        public double ExcavAvgAdjKU { get; set; }
        public double ExcavAvgAdjKL { get; set; }
        public double ExcavAvgAdjSP { get; set; }

        // ── Per-station cross-sections (populated by BoQParserService) ────────
        public List<CrossSectionStation> Stations { get; set; } = new List<CrossSectionStation>();
    }

    // =========================================================================
    // Phase 1 – Aggregate report
    // =========================================================================

    public class BoQReport
    {
        public DateTime              GeneratedAt    { get; set; } = DateTime.Now;
        public List<SystemBoQ>       Systems        { get; set; } = new List<SystemBoQ>();
        public List<string>          DiscoveryNotes { get; set; } = new List<string>();
        public List<SectionDebugRow> SectionDebug   { get; set; } = new List<SectionDebugRow>();

        public double TotalPipeLength =>
            Systems.SelectMany(s => s.Pipes).Sum(p => p.TotalLength);

        public int TotalManholeCount =>
            Systems.SelectMany(s => s.Manholes).Sum(m => m.Count);

        public double TotalExcavationVolume =>
            Systems.SelectMany(s => s.Pipes).Sum(p => p.TotalExcavationVolume);

        public double TotalBeddingVolume =>
            Systems.SelectMany(s => s.Pipes).Sum(p => p.TotalBeddingVolume);

        public double TotalSurroundVolume =>
            Systems.SelectMany(s => s.Pipes).Sum(p => p.TotalSurroundVolume);

        public double TotalBackfillVolume =>
            Systems.SelectMany(s => s.Pipes).Sum(p => p.TotalBackfillVolume);

        public double TotalOverlapVolumeDeducted =>
            Systems.SelectMany(s => s.Pipes).Sum(p => p.OverlapVolumeDeducted);
    }

    // =========================================================================
    // Phase 2 – Manhole AI catalog models
    // =========================================================================

    /// <summary>
    /// One row from the Manhole_Catalog.xlsx template (new row-per-part schema).
    ///
    /// Catalog columns: Nominal_Diameter | Part_Name | Height_m | Is_Mandatory | Is_Variable_Ring
    /// </summary>
    public class CatalogPart
    {
        /// <summary>Part label as written in the catalog, e.g. "Taban", "Konik", "Govde".</summary>
        public string PartName       { get; set; }
        /// <summary>Height of this component in metres.</summary>
        public double HeightM        { get; set; }
        /// <summary>True → always add exactly 1 unit per manhole regardless of depth.</summary>
        public bool   IsMandatory    { get; set; }
        /// <summary>True → eligible for the greedy height-filling algorithm.</summary>
        public bool   IsVariableRing { get; set; }
    }

    /// <summary>
    /// All catalog parts for one nominal manhole diameter.
    /// Populated by ManholeAIService.ReadCatalog().
    /// </summary>
    public class CatalogEntry
    {
        /// <summary>Manhole shaft internal diameter (mm).</summary>
        public int NominalDiameter { get; set; }

        /// <summary>All parts defined for this diameter in the catalog.</summary>
        public List<CatalogPart> Parts { get; set; } = new List<CatalogPart>();

        /// <summary>Parts where IsMandatory == true (always 1 unit per manhole).</summary>
        public List<CatalogPart> MandatoryParts =>
            Parts.Where(p => p.IsMandatory).ToList();

        /// <summary>
        /// Parts where IsVariableRing == true, sorted largest → smallest.
        /// Used by the greedy stacking algorithm.
        /// </summary>
        public List<CatalogPart> VariableRings =>
            Parts.Where(p => p.IsVariableRing)
                 .OrderByDescending(p => p.HeightM)
                 .ToList();

        /// <summary>Sum of heights of all mandatory parts (fixed stack base height).</summary>
        public double TotalMandatoryHeight =>
            Parts.Where(p => p.IsMandatory).Sum(p => p.HeightM);
    }

    // =========================================================================
    // Phase 2 – Stacking result models
    // =========================================================================

    /// <summary>
    /// One concrete part entry in a manhole's stack.
    /// Mandatory parts always have Count == 1.
    /// Variable rings may have Count > 1.
    /// </summary>
    public class StackedPart
    {
        /// <summary>Part name from the catalog (e.g. "Taban", "Govde").</summary>
        public string PartName       { get; set; }
        /// <summary>Height of this part (m).</summary>
        public double HeightM        { get; set; }
        /// <summary>Number of identical units stacked.</summary>
        public int    Count          { get; set; }
        /// <summary>True if this part was selected by the greedy ring algorithm.</summary>
        public bool   IsVariableRing { get; set; }
    }

    /// <summary>
    /// Complete stacking solution for one manhole.
    /// </summary>
    public class ManholeStackResult
    {
        public int  NominalDiameter { get; set; }
        /// <summary>True = pre-cast discrete parts; false = cast-in-place concrete pour.</summary>
        public bool IsPreCast       { get; set; }

        /// <summary>
        /// Ordered list of all stacked parts:
        ///   mandatory parts first (in catalog order), then variable rings (largest first).
        /// </summary>
        public List<StackedPart> Parts { get; set; } = new List<StackedPart>();

        /// <summary>
        /// Height gap remaining after all rings have been stacked (metres).
        /// Should be ≤ LeftoverTolerance (0.05 m) after the algorithm runs.
        /// </summary>
        public double ResidualM { get; set; }

        // ── Cast-in-place only ────────────────────────────────────────────────
        /// <summary>Total concrete shaft depth in metres (IsPreCast == false only).</summary>
        public double ConcreteDepth { get; set; }
    }
}
